// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, task, done)
VALUES (NULL, ?, ?)
RETURNING id, task, done
`

type CreateTodoParams struct {
	Task sql.NullString
	Done sql.NullBool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Task, arg.Done)
	var i Todo
	err := row.Scan(&i.ID, &i.Task, &i.Done)
	return i, err
}

const deleteAllDone = `-- name: DeleteAllDone :exec
DELETE FROM todos
WHERE done = 1
`

func (q *Queries) DeleteAllDone(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDone)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, task, done FROM todos
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(&i.ID, &i.Task, &i.Done)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, task, done FROM todos
ORDER BY id
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Task, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos SET task = ?, done = ?
WHERE id = ?
`

type UpdateTodoParams struct {
	Task sql.NullString
	Done sql.NullBool
	ID   int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo, arg.Task, arg.Done, arg.ID)
	return err
}
